### ISSUE TITLE
Ability to provide a custom certificate authority bundle to the acorn control plane

### ISSUE THREAD

**Issue by cjellick** [acorn-io/acorn#1037]
When an organization uses an internal registry, it is often secured with a TLS certificate signed by a private Certificate Authority. When that's the case, clients will only trust the certificate presented by the registry if the signing authority is in the CA bundle that the client has access to. In containerized applications, the CA is usually whatever is part of the base OS of the container. This is the case with the acorn control plane components: api-server, controller, builders.

So, to allow these components to properly integrate with the registry, we need to give the person installing/administering the acorn control plane a way to override the default CA bundle.

Proposed solution is for the administrator to put their CA bundle into a secret that will be recognized by the acorn installation process and bound into the acorn control plane components.

**Comment by StrongMonkey** [comment]
@sangee2004 this is how I test this during development, but take it as a grain of salt.

### Prepare a registry

First you will need to make sure the registry runs in static IP/hostname so that you can put the SAN into your self-signed certificate. I run registry in Digitialocean.

1. Create a digitalocean instance. Generate a certificate with the public IP of the instance.

```
openssl req -x509 -nodes -days 825 -newkey rsa:4096 \
    -addext "subjectAltName = IP:$replace_your_ip" \
    -keyout server.key -out server.crt
```

2. Run the registry service with the certs mounted.

```
docker run -d \
  --restart=always \
  --name registry \
  -v /path/to/server.crt:/certs/server.crt -v /path/to/server.key:/certs/server.key \
  -e REGISTRY_HTTP_TLS_CERTIFICATE=/certs/server.crt \
  -e REGISTRY_HTTP_TLS_KEY=/certs/server.key -e REGISTRY_HTTP_ADDR=0.0.0.0:443\
  -p 443:443 \
  registry:2
```

### Generate a **full** CA chain with the private CA include.

Since we are replacing the whole CA chain in acorn controlplane, you will need to grab the full chain, otherwise acorn won't be able to trust other CAs. To do so, I run ubuntu container and just copy the certs out.


```
docker run -it ubuntu sleep 10000

docker cp $ubuntu_container_id:/etc/ssl/certs/ca-certificates.crt ~/ca-certificates.crt
```

### Append your private CA

Now append the private CA into the cert you just copied, and create secrets based on the file

```
cat ~/server.crt >> ~/ca-certificates.crt

kubectl -n acorn-image-system create secret generic cabundle --from-file=ca-certificates.crt=~/ca-certificates.crt

kubectl -n acorn-system create secret generic cabundle --from-file=ca-certificates.crt=~/ca-certificates.crt
```

### Install acorn with custom bundle options and also point it to the private registry.

```
acorn install --internal-registry-prefix "$IP/" --use-custom-cabundle
```

### Test

Now test if you can use acorn to build and run apps. You should be able to push acorn image into the internal registry and run the app with the image.

**Comment by cjellick** [comment]
@jsilverio22 and @tylerslaton to test this

**Comment by StrongMonkey** [comment]
@jsilverio22 One thing I forgot to mention, is that after you setup your insecure registry, make sure you install acorn **without** custom certs to see if it fails, and then install **with** the cert, and make sure the app went through.

**Comment by jsilverio22** [comment]
@tylerslaton and I QA Steps:

### Prepare a registry

First you will need to make sure the registry runs in static IP/hostname so that you can put the SAN into your self-signed certificate. I run registry in Digitialocean.

1. Created a digitalocean droplet. and generated a certificate with the public IP of the instance.

```
openssl req -x509 -nodes -days 825 -newkey rsa:4096 \
    -addext "subjectAltName = IP:<IP>" \
    -keyout server.key -out server.crt
```

2. Ran the registry service with the certs mounted.

```
docker run -d \
  --restart=always \
  --name registry \
  -v /path/to/server.crt:/certs/server.crt -v /path/to/server.key:/certs/server.key \
  -e REGISTRY_HTTP_TLS_CERTIFICATE=/certs/server.crt \
  -e REGISTRY_HTTP_TLS_KEY=/certs/server.key -e REGISTRY_HTTP_ADDR=0.0.0.0:443\
  -p 443:443 \
  registry:2
```

1. Generated a full CA chain on local comp

```
docker run -it ubuntu sleep 10000

docker exec -it container-id bash
apt update && apt install ca-certificates -y
exit

docker cp $ubuntu_container_id:/etc/ssl/certs/ca-certificates.crt ~/ca-certificates.crt
```

1. Append  private CA

```
cat ~/server.crt >> ~/ca-certificates.crt

kubectl -n acorn-image-system create secret generic cabundle --from-file=ca-certificates.crt=~/ca-certificates.crt

kubectl -n acorn-system create secret generic cabundle --from-file=ca-certificates.crt=~/ca-certificates.crt
```
1. Installed acorn and built image attempt to push

```
$ acorn install 
$ acorn build . -t registry-ip/test:latest .
$ acorn push registry-ip/test:latest
  ✗  ERROR:  Get "https://164.92.91.43/v2/": x509: certificate signed by unknown authority

```
1. Reinstall with ca cert bundle

```
$ acorn install --use-custom-ca-bundle
$ acorn build . -t registry-ip/test:latest .
$ acorn push registry-ip/test:latest
   [110887131/110887131] ██████████████████████████████████████████████ 100% | 13s
```
Check registry on DO droplet to make sure it successfully pushed

```
$docker login localhost
Username: username
Password: 
WARNING! Your password will be stored unencrypted in /root/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store

Login Succeeded
$ docker pull localhost/test
Using default tag: latest
latest: Pulling from test
no matching manifest for linux/amd64 in the manifest list entries
```
acorn image so won't pull completely confirmed with a image not in registry 

```
$ docker pull localhost/foo
Using default tag: latest
Error response from daemon: manifest for localhost/foo:latest not found: manifest unknown: manifest unknown
```

1. Make sure we can revoke cert through flag
```
$ acorn install --use-custom-ca-bundle=false
$ acorn build . -t registry-ip/testnowork:latest .
$ acorn push registry-ip/testnowork:latest
  ✗  ERROR:  Get "https://164.92.91.43/v2/": x509: certificate signed by unknown authority
```
