### ISSUE TITLE
Disable the feature that allows users to set labels and annotations

### ISSUE THREAD

**Issue by cjellick** [acorn-io/acorn#1041]
We introduced a feature that allows labels and annotations to be set in an acornfile or as part of `acorn run` and have those be propagated down through the native kubernetes objects. That feature is described here:
- https://docs.acorn.io/authoring/labels
- https://docs.acorn.io/running/labels

We need an install flag that can turn this feature completely off. We want to be able to turn it off because it poses a security concern in Hub. Setting labels/annotations could allow a user to opt pods into permissions or abilities that they shouldn't have.

**Comment by sangee2004** [comment]
Tested with `acorn version v0.5.0-rc3-9-g4e16d33+4e16d334`

 
1.  Default value  for  `ignore-user-labels-and-annotations` is false. User is allowed to create apps with user labels and annotations.
2. Once this flag id set to `true`, all existing pods with user labels and annotations get redeployed with no user labels and annotations.
3. When this flag is set to `false` , all existing pods with user labels and annotations get redeployed with all the user labels and annotations that were ignored  because of this flag being set to `true`
4. With this flag set to `true`, creating/updating new apps with the labels and annotation ignores labels and annotations silently and pods don’t get the  labels/annotations passed in the Acorn file using `acorn run` and `acorn run —update`.
  5. With flag set to `true`,  creating/updating new apps with the labels and annotation ignores labels and annotations silently and pods don’t get the  labels/annotations set using `—label` and `—annotation`  flags in `acorn run` and `acorn update`.   All the above behaviors are also seen with secrets and volumes.
