### ISSUE TITLE
Not able to set any acorn arguments when running apps in auto upgrade format.

### ISSUE THREAD

**Issue by sangee2004** [acorn-io/acorn#1056]
acorn version v0.5.0-rc2-2-g6cee142+6cee1422 

While trying to run an app in auto upgrade mode with invalid acorn arguments , parsing error is presented to the user which does not provide any useful information.
```
% acorn run index.docker.io/xxx/xxx:v#.#.# --interval 3
  ✗  ERROR:  could not parse reference: index.docker.io/sangeetha/myfirstacorn:v#.#.#
```

The same scenario is handled with better error message when not using auto upgrade mode .
```
 % acorn run index.docker.io/xx/xxx:v2.0.0 --interval 3
  ✗  ERROR:  unknown flag: --interval
```

The bigger issue here is that we are not able to set any acorn arguments when running apps in auto upgrade mode.

This run command works as expected when passing a valid acorn argument.
```
acorn run -n testlocalold mytest1:v0.0.2 --new=false 
```

When we try to run the same app in auto upgrade mode with args passed it fails with following error message:

```
%acorn run -n testlocalold mytest1:v#.#.# --new=false 
  ✗  ERROR:  could not parse reference: mytest1:v#.#.#

% acorn run -n testlocalold "mytest1:v#.#.#" --new=false 
  ✗  ERROR:  could not parse reference: mytest1:v#.#.#
```

**Comment by thedadams** [comment]
This is actually not an error message problem.

The args passed after the image are "acorn args." In order to determine if the passed args are valid for an Acorn, the CLI will look at the Acorn image and parse its args.

In the case where you are providing an auto-upgrade image format, Acorn doesn't know which Acorn image to pull which causes the error. You get a different error when you pass a real image name because Acorn pulls the image and sees that the Acorn doesn't have an `--interval` option.

@cjellick Is this something we want to support?

**Comment by sangee2004** [comment]
This problem happens even when valid acorn arguments are passed. I am changing the bug description to reflect this.

**Comment by sangee2004** [comment]
Tested with `acorn version v0.5.1-28-g099c492+099c492f`

We are now able to set acorn arguments when launching apps in auto upgrade format.
When invalid acorn arguments are passed , user is presented with an error message.

```
% acorn run --interval=1m -n myt2 mynew:#.#.# --xx=false
  ✗  ERROR:  unknown flag: --xx
% acorn run --interval=1m -n myt2 mynew:#.#.# --new=false --xx=false
  ✗  ERROR:  unknown flag: --xx
 % acorn run --interval=1m -n myt2 mynew:#.#.# --new=false           
myt2
STATUS: ENDPOINTS[] HEALTHY[] UPTODATE[] 
STATUS: ENDPOINTS[] HEALTHY[0] UPTODATE[0] pending
STATUS: ENDPOINTS[] HEALTHY[0/1] UPTODATE[1] [containers: nginx1 ContainerCreating]
...

```
