### ISSUE TITLE
acorn update refactor

### ISSUE THREAD

**Issue by sangee2004** [acorn-io/acorn#1059]
Following are the different ways supported for updating apps:

The different is basically POST, PUT, PATCH.  POST is create, PUT is update ALL fields explicitly to the passed values, and PATCH is add new fields or change field values to the passed values

acorn run = POST
acorn run --update = PUT
acorn update = PATCH
acorn update --replace = PUT

Since `acorn run --update` and `acorn udpate --replace` do the same thing , making `update` basically an alias to `run --update` would help. As part of this change , update  should also start taking directory.

**Comment by cjellick** [comment]
@ibuildthecloud i cant recall if you're doing this or someone else should pick it up

**Comment by cjellick** [comment]
Notes from most recent convo with darren: 
    ◦ changing run and update

        ▪ flip the behave
        ▪ run is create
        ▪ run —update is patch
        ▪ run —replace is set it exactly as i say
        ▪ for all of those, they need to support building the iamge (.)
    ◦ acorn update becomes syn for run —update
    ◦ acorn dev is a syn for run —dev but also default to current dir
    ◦ consistency with .

**Comment by jsilverio22** [comment]
unify run / update update becomes alias add dev subcmd

acorn run -> create new resource if name exits fail
acorn run --update should update existing resource or create only updates info from cli (PATCH) (possible to have 0 args) update args with no image? acorn run --update -- args  
acorn update args -> patch args 
acorn run --replace -> need all other args
acorn run --replace create or update a running app w/ exact flags passed

acorn update becomes syn for acorn run --update image is a flag (--iamge) rather than args

acorn dev -> acorn run w/ --dev

anywhere image has to work for a dir same w/ dev 
acorn dev w/ no image == attach dev session to currently running app
acorn dev imagename -> dev session

acorn update gen through redeploy flag  timestamp annotation? just has to be unique acorn update --touch --recalculate --refresh --?


confirm upgrade
acorn update --confirm-upgrade stays
acorn update --pull forces image recalc add to acorn run (should pull latest)
acorn run --pull (and not autoupdate) and image refers to image that is pulled locally should still re-pull

**Comment by jsilverio22** [comment]
acorn run should only take app name as flag (acorn run white-snow) should be acorn run --name white-snow

**Comment by sangee2004** [comment]
Related issue - https://github.com/acorn-io/acorn/issues/1448

**Comment by cjellick** [comment]
assigning this over to darren as he's going to impl the tweaks he wants to see

**Comment by sangee2004** [comment]
2 Major issues https://github.com/acorn-io/acorn/issues/1470 and https://github.com/acorn-io/acorn/issues/1448 have been addressed.

Issues found when testing with acorn version v0.6.0-158-g3b6f3c99+3b6f3c99 which has the second round of update refactor is tracked in https://github.com/acorn-io/acorn/issues/1487.
