### ISSUE TITLE
Potential Horizontal Privilege Escalation Concern

### ISSUE THREAD

**Issue by gwen-madd** [acorn-io/acorn#1060]
Hey y'all!

I was doing some research on the acorn product and going through docs. I noticed y'all have defined Verbs for Permissions in your Acornfile definitions here: https://docs.acorn.io/authoring/permissions#verbs

I noticed in the appspec, the permission struct is a mapping directly to k8s rbac struct here: https://github.com/acorn-io/acorn/blob/main/pkg/apis/internal.acorn.io/v1/appspec.go#L236

From what I can tell, there are some additional verbs such as `escalate`, `impersonate` and `bind` here: https://kubernetes.io/docs/reference/access-authn-authz/authorization/#determine-the-request-verb

that can be assigned to User created roles from the acornfile. The k8s documentation does specify there are authorization checks against the definitions of those values before they're assigned, but I wasn't sure on how the roles were created via the acorn file. If the user that creates those roles had k8s level authorization, the newly created role could then generate roles with escalated privileges, and assume up to admin.

Please disregard if the k8s authorization checks would stop this from happening, or if you have other validation means to keep assigned verbs to exactly the set you've described in the documentation.

**Comment by cjellick** [comment]
Thanks for the report. This should be covered and prevented via our escalation checks (which in turn use native k8s escalation checks), but i'm going to run through a few scenarios just to be sure. Will report back.

**Comment by cjellick** [comment]
Confirm this isn't an issue and that we prevent it. Here's what I did:

### First, create an uprivileged user 
I'm testing locally against rancher desktop, so I just configured one in my kubeconfig to use my normal rancher-desktop user, but "as" a user named "un-priv":
```
...
users:
- name: rd-unpriv
    user:
      client-certificate-data: ...
      client-key-data: ...
      as: un-priv
...
contexts:
- name: rd-unprivileged
    context:
      cluster: rancher-desktop
      name: rancher-desktop
      user: rd-unpriv
```
Give the user "rd-unpriv" limited permissions:
```
kubectl --namespace acorn create rolebinding --clusterrole edit --user un-priv un-priv-acorn-edit
kubectl --namespace acorn create rolebinding --clusterrole 'acorn:project:edit' --user un-priv un-priv-acorn-project-edit
```
Note that the cluster role "acorn:project:edit" doesn't exist in v0.4.2 of acorn, but it is coming in the next release. It's perms are [here](https://github.com/acorn-io/acorn/blob/main/pkg/roles/roles.go). Suffice it to say, it let's you deploy acorn apps, but doesn't give admin perms.

### Create an acorn that attempts to escalate
Create an acorn with some permissions that would theoretically do the escalation described. Here's the Acornfile:
```
args: {
	// App version
	version: "b"
}

containers: {
	mycon1: {
		image: "nginx"
		ports: {
			publish: "80/http"
		}
		scale: 1
		files: {
			// Simple index.html file
			"/usr/share/nginx/html/index.html": "<h2>Bersion: \(args.version)</h2><img src='https://c.tenor.com/x8v1oNUOmg4AAAAd/rickroll-roll.gif'/> "
		}
		permissions: {
			clusterRules: [{
				verbs: ["escalate"]
				apiGroups: ["rbac.authorization.k8s.io"]
				resources: ["roles", "clusterroles"]
			}]
		}
	}
}
```
Excuse the unrelated fluff. It's my standard scratch acornfile. I built that via:
```
acorn build -t escalation-test .
```

### Assume the role of the new user
I use a tool called `kubechc` to switch between k8s contexts.
```
kubechc rd-unprivileged
```
Prove I have limited perms:
```
$ kubectl get nodes
Error from server (Forbidden): nodes is forbidden: User "un-priv" cannot list resource "nodes" in API group "" at the cluster scope

$ acorn --namespace default ps
Error: apps.api.acorn.io is forbidden: User "un-priv" cannot list resource "apps" in API group "api.acorn.io" in the namespace "default"

$ acorn ps
NAME      IMAGE     HEALTHY   UP-TO-DATE   CREATED   ENDPOINTS   MESSAGE
```
That shows I can only successfully list apps in the `acorn` namesapce.

### Attempt to deploy the acorn image with the escalation:
```
acorn run escalation-test
  •  WARNING:  This application would like to request the following runtime permissions.
                 This could be VERY DANGEROUS to the cluster if you do not trust this
                 application. If you are unsure say no.

SERVICE   VERBS      RESOURCE                                 SCOPE
mycon1    escalate   roles.rbac.authorization.k8s.io          cluster
mycon1    escalate   clusterroles.rbac.authorization.k8s.io   cluster

? Do you want to allow this app to have these (POTENTIALLY DANGEROUS) permissions? Yes
Error: App.api.acorn.io "rough-leaf" is invalid: spec.permissions: Invalid value: []v1.Permissions{v1.Permissions{ServiceName:"mycon1", Rules:[]v1.PolicyRule(nil), ClusterRules:[]v1.PolicyRule{v1.PolicyRule{Verbs:[]string{"escalate"}, APIGroups:[]string{"rbac.authorization.k8s.io"}, Resources:[]string{"roles", "clusterroles"}, ResourceNames:[]string(nil), NonResourceURLs:[]string(nil)}}}}: not authorized: {"verbs":["escalate"],"apiGroups":["rbac.authorization.k8s.io"],"resources":["roles","clusterroles"]}
```
You can see that after saying yes, the API request to create the App failed because I (the unprivileged user) did not have the necessary permissions.
