### ISSUE TITLE
New propagateProjectLabels and propagateAnnotations feature

### ISSUE THREAD

**Issue by StrongMonkey** [acorn-io/acorn#1172]
## Context

Starting at v0.6.0, we are adding two new flags in `acorn install` to allow labels and namespaces propagation . This allows to acorn to propagate specified labels and annotations from project down to app namespaces.

## How to use

When installing acorn, user has to specify the labels and annotation keys they want to propagate.

```
acorn install --propagate-project-annotation "linkerd.io/inject"
```

After that, if you add this annotation `linkerd.io/inject: enabled` to your project, any app launched in this project should have a namespace that is annotated with  `linkerd.io/inject: enabled`.

The main use case for this is to do automatic annotations/labels on app namespace to allow sidecar injections. For example, our linkerd-plugin will automatically add `linkerd.io/inject: enabled` to any acorn project to automatically inject anotations.

**Comment by StrongMonkey** [comment]
As @sangee2004 pointed out, there is currently no way to change the project annotation through acorn cli.

The main driven case here is for linkerd plugin. This is the workflow

1. User configures propagatetion setting through acorn to propagate `linkerd.io/inject`
2. User install linkerd-plugin, it autonmatically addes annotation to all projects.
3. Acorn propagates annotation down to evert app namespace in each project, make sure each app is injected with sidecar.

**Comment by sangee2004** [comment]
Tested with version: `v0.5.1-5-g28a7873+28a78730`


Annotation and Label propagation:

1. Set  labels and annotations to be propagated  using `acorn install --propagate-project-annotation a1/test1 --propagate-project-label label/test2` 
2. Create a project.
3. Deploy app - app1
4. Add labels and annotations to the project namespace . Have labels and annotations that match the `propagate-project-annotation`  and `propagate-project-label` setting and have few of them that dont match.
5. Namespace relating to app1 gets the label and annotations sets at the project level that matches with `propagate-project-annotation` and `propagate-project-label`
6. Deploy more apps - say app2.
7.  Namespace relating to app1 gets the label and annotations sets at the project level that matches with `propagate-project-annotation` and `propagate-project-label`

Edit labels and annotation for the projects:

1. Edit existing labels and annotations to the project namespace  by removing existing labels/annotation and editing label values/annotation.
2. Label and Annotation changes (including removal) get propagated to  namespaces relating to app1 and app2 


Modify `--propagate-project-annotation` and `--propagate-project-label`  using `acorn --install` 

1. Modify `--propagate-project-annotation` and `--propagate-project-label`  using `acorn --install` so that there are new labels/annotations that match the labels and annotations preset in project namespace added and existing matched ones removed from the setting. 
 
3. Label and Annotation changes (including removal) get propagated to  namespaces relating to app1 and app2 

`linkerd.io/inject` feature itself is not tested as part of this issue.
