### ISSUE TITLE
Volume class information missing when binding to existing volumes

### ISSUE THREAD

**Issue by thedadams** [acorn-io/acorn#1420]
1. Create an app that uses a volume
2. Delete the app without using `-af` so that volume is leftover.
3. Wait for volume to be released
4. Create another app (can be same app, but with different name) and bind the volume with `-v pvc-...:vol-name`.

Once the app is up and running `acorn volume` will not show volume class information for the volume.

**Comment by sangee2004** [comment]
Duplicate - https://github.com/acorn-io/acorn/issues/1311

**Comment by sangee2004** [comment]
Tested with  `acorn version v0.6.0-113-g83b7b9f3+83b7b9f3`

volumes have volume-class set when they get bound to an App.

Deploy app `testvoldata` with vol - `my-data`.
```
% acorn volumes
ALIAS                         NAME                                       APP-NAME         BOUND-VOLUME   CAPACITY   VOLUME-CLASS   STATUS     ACCESS-MODES   CREATED
testvoldata.my-data           pvc-b3d31c1a-488c-458a-b58c-4181b62fb625   testvoldata      my-data        10G        local-path     bound      RWO            6s ago
```

Delete App without removing volumes so that they get to "released" state.
```
 % acorn volumes
ALIAS                         NAME                                       APP-NAME         BOUND-VOLUME   CAPACITY   VOLUME-CLASS   STATUS     ACCESS-MODES   CREATED
testvoldata.my-data           pvc-b3d31c1a-488c-458a-b58c-4181b62fb625   testvoldata      my-data        10G        local-path     released   RWO            21s ago
```

Deploy app `testvolbind`  and bind it to existing volume `pvc-b3d31c1a-488c-458a-b58c-4181b62fb625`.
Once app gets deployed successfully , `volume class` on the volumes is set to "local-path" as expected.

```
 % acorn volumes
ALIAS                         NAME                                       APP-NAME         BOUND-VOLUME   CAPACITY   VOLUME-CLASS   STATUS     ACCESS-MODES   CREATED
testvolbind.my-data-bind      pvc-b3d31c1a-488c-458a-b58c-4181b62fb625   testvolbind      my-data-bind   10G        local-path     bound      RWO            55s ago
```
