### ISSUE TITLE
Service leftover after app is deleted

### ISSUE THREAD

**Issue by thedadams** [acorn-io/acorn#1423]
1. Create an app with a custom hostname published to a port in the app (i.e. -p thedadams.com:site:80)
2. Wait for app to be ready.
3. Delete the app

A service in the acorn namespace with the same name as the app will be leftover. Launching the app again with the same name will cause errors to appear in the controller such as
```
time="2023-04-01T21:41:06Z" level=error msg="error syncing '_t thedadams-site-2821127a-864/site': handler acorn-controller internal.acorn.io/v1, Kind=ServiceInstance: failed to update existing owned object acorn/thedadams-site /v1, Kind=Service for acorn-controller thedadams-site-2821127a-864/site, old subcontext [acorn-controller] gvk [internal.acorn.io/v1, Kind=ServiceInstance] namespace [thedadams-site-cf711a04-f7d] name [site]: services \"thedadams-site\" already exists, requeuing"
```

**Comment by sangee2004** [comment]
This issue was also seen when apps were deployed with published ports.

Tested with acorn version v0.6.0-113-g83b7b9f3+83b7b9f3

Deploy app - testp with  custom hostname published to a port in the app.
Deploy app - test  with  published port.
```
kubectl get service -n acorn       
NAME    TYPE           CLUSTER-IP   EXTERNAL-IP                                  PORT(S)   AGE
testp   ExternalName   <none>       myweb.testp-6a24c04d-8c9.svc.cluster.local   80/TCP    2m57s
test    ExternalName   <none>       myweb.test-42be7a8d-734.svc.cluster.local    80/TCP    34s
```

Deplete the apps

 ~ % kubectl get service -n acorn
No resources found in acorn namespace.

ExternalName service gets deleted as expected.

Redeploying the same apps again  succeeds and no error messages relating to "failed to update existing owned object" is seen in controller logs.
