### ISSUE TITLE
acorn run --update will not create if --name is set 

### ISSUE THREAD

**Issue by jsilverio22** [acorn-io/acorn#1444]
`acorn run --update -n new-app .`
will fail as new-app does not exist 

expected behavior should mirror `acorn run -n new-app`

**Comment by sangee2004** [comment]
Tested with `acorn version v0.6.0-135-ga2ab14b5+a2ab14b5`

New app gets created now when running any of the commands:

`acorn run --update -n <app that does not exist>`
`acorn run --update -n <app that does not exist> .`
`acorn run --replace -n <app that does not exist>`
`acorn run --replace -n <app that does not exist> .`
`acorn update -n <app that does not exist>`
`acorn update -n <app that does not exist> .`

It is not desirable for `acorn update` to be creating new resources . This issue is tracked in https://github.com/acorn-io/acorn/issues/1448
