### ISSUE TITLE
Endpoint urls do not resolve.

### ISSUE THREAD

**Issue by sangee2004** [acorn-io/acorn#1628]
acorn version v0.7.0-alpha1-67-g64d4d520+64d4d520

Steps to reproduce the problem:
Deploy apps with published port and try to access the endpoint url.
```
curl http://myweb1-mytest1-d1485bf1.local.oss-acorn.io
curl: (6) Could not resolve host: myweb1-mytest1-d1485bf1.local.oss-acorn.io
```

**Comment by cjellick** [comment]
@njhale  this is caused by a change in the way we manage records. Specifically, local.oss-acorn.io is now created in the same route53 zone that acorn-dns is managing. Acorn dns has "garbage collection" logic where it will delete records from route53 if a corresponding record doesn't exist in its database.

That logic is here: https://github.com/acorn-io/acorn-dns/blob/main/pkg/backend/purger.go#L21

The way that logic works, we get back the records from the zone create a collection of the records that dont have a corresponding entry in our db (that happens here: https://github.com/acorn-io/acorn-dns/blob/main/pkg/backend/purger.go#L58-L65)

Once we get through all the pages of records returned by route53, we delete whatever is in the collection. So, I think you just need to add some logic once we're outside of the pagination loop (like maybe right above here https://github.com/acorn-io/acorn-dns/blob/main/pkg/backend/purger.go#L74) that deletes "exempt" records from the collection of records to be deleted.

**Comment by njhale** [comment]
This should be fixed by https://github.com/acorn-io/acorn-dns/pull/70

**Comment by sangee2004** [comment]
Endpoint url resolutions works as expected.
