### ISSUE TITLE
Support leader probe and election for the acorn control plane

### ISSUE THREAD

**Issue by ibuildthecloud** [acorn-io/acorn#241]

**Comment by cjellick** [comment]
Here's the next up for you @thedadams

**Comment by cjellick** [comment]
@thedadams can you add in details here about what we're doing and why.

**Comment by thedadams** [comment]
Leader election is being added to `acorn-controller`. The plan, at this point, is not to have multiple instances of the controller running at any one time because there would be nothing for he second instance to do. It would just sit with the log message `leaderelection.go:248] attempting to acquire leader lease kube-system/acorn-controller...`

The reason for this is around upgrades. Currently, when the user upgrades to a new version of Acorn, there may be contention as the new pod comes up and before the old pod is destroyed. This could cause some raciness in Acorn or noisiness with the Kubernetes API.

With this implementation, the new pod will come up and wait to acquire the leader lease (as the log message above says) and will only fully start once it becomes the leader.

Note that this won't happen when you upgrade TO this new version because the older version doesn't have leader election. The newer version will successfully acquire the lease and start up. Both the older version and newer version would need to have leader election support.

With that said, the easiest way to test this is to scale the `acorn-controller` to 2 and look at the logs of the new pod. You should see the above log message and it will just sit there.

**Comment by sangee2004** [comment]
Tested with Acorn version -`v0.5.1+46fe4aef`

Increase the acorn-controller deployment's replica to 2 , this results in 2 `acorn-controller` pods.

One of the pods is fully functioning a a controller and other pod just waits to acquire the leader lease.

logs from this pod:

```
 ~ % kubectl logs acorn-controller-7749fc77f-rbknj -n acorn-system
time="2023-01-31T01:20:31Z" level=info msg="Applying CRD appinstances.internal.acorn.io"
time="2023-01-31T01:20:31Z" level=info msg="Applying CRD acornimagebuildinstances.internal.acorn.io"
time="2023-01-31T01:20:31Z" level=info msg="Applying CRD builderinstances.internal.acorn.io"
time="2023-01-31T01:20:31Z" level=info msg="Applying CRD imageinstances.internal.acorn.io"
I0131 01:20:31.134707       1 leaderelection.go:248] attempting to acquire leader lease kube-system/acorn-controller...
```

When this pod is deleted , the new pod that gets created again waits to acquire the leader lease.


When the leader pod is deleted , the new pod that gets created still assume the leader role.
