### ISSUE TITLE
Error on uninstall

### ISSUE THREAD

**Issue by cjellick** [acorn-io/acorn#664]
When I run uninstall, I now very consistently get "an empty namespace may not be set with a resource name provider":

```
corn $ acorn uninstall -af
  •  Deleting v1.api.acorn.io APIService apiregistration.k8s.io/v1
  •  Deleting acorn-system ClusterRole rbac.authorization.k8s.io/v1
  •  Deleting traefik ClusterRole rbac.authorization.k8s.io/v1
  •  Deleting acorn-system ClusterRoleBinding rbac.authorization.k8s.io/v1
  •  Deleting acorn-system/traefik ClusterRoleBinding rbac.authorization.k8s.io/v1
  •  Deleting acorn-system/acorn-config ConfigMap v1
  •  Deleting appinstances.internal.acorn.io CustomResourceDefinition apiextensions.k8s.io/v1
  •  Deleting acorn-system/acorn-api Deployment apps/v1
  •  Deleting acorn-system/acorn-controller Deployment apps/v1
  •  Deleting acorn-system/traefik Deployment apps/v1
  •  Deleting traefik IngressClass networking.k8s.io/v1
  •  Deleting acorn-system/acorn-dns Secret v1
  •  Deleting acorn-system/acorn-api Service v1
  •  Deleting traefik Service v1
  •  Deleting acorn-system/acorn-system ServiceAccount v1
  •  Deleting acorn-system/traefik ServiceAccount v1
  •  Deleting acorn Namespace v1
  •  Deleting acorn-system Namespace v1
Error: an empty namespace may not be set when a resource name is provided
```

and the uninstall process immediately exits, even though it isnt really done

**Comment by bigkevmcd** [comment]
This is because...

https://github.com/acorn-io/acorn/blob/main/pkg/install/install.go#L255-L260
```go
objs, err := traefikResources()
if err != nil {
	return err
}

return apply.WithSetID("acorn-install-traefik").WithDefaultNamespace(system.Namespace).ApplyObjects(objs...)
```
Applies the [system.Namespace](https://github.com/acorn-io/acorn/blob/main/pkg/system/constants.go#L6) as the default namespace to the Traefik resources when they're being installed...but...

https://github.com/acorn-io/acorn/blob/main/pkg/uninstall/uninstall.go#L93-L100
```go
traefikResources, err := install.TraefikResources()
if err != nil {
    return nil, err
}
resources = append(resources, traefikResources...)
```
Causes them to be deleted without a namespace (the YAML for the resource has no namespace https://github.com/acorn-io/acorn/blob/main/pkg/install/traefik.yaml#L209)

This is a quick fix by [applying the namespace](https://github.com/acorn-io/acorn/compare/main...bigkevmcd:acorn:issue-664-traefik-service-namespace) which is the same as the accompanying `Deployment` https://github.com/acorn-io/acorn/blob/main/pkg/install/traefik.yaml#L83

**Comment by cjellick** [comment]
Ah!

**Comment by meldafrawi** [comment]
Validation: **PASS**

tested on Docker Desktop v4.12.0
